In [4]:
li=[i**4 for i in range(1,8)]
%timeit li

21.7 ns ± 0.179 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [6]:
import numpy as np
%timeit np.arange(1,8)**4

2.7 µs ± 52.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
import numpy as np
li=[[i for i in range(5)] for j in range(5)]
print(li)
nli=np.array(li)
print(nli.ndim)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
2


In [14]:
import numpy as np
li=[[[k for k in range(5)] for i in range(5)] for j in range(5)]
nli=np.array(li)
print(li)
print("dimension=",nli.ndim)

[[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]], [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]], [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]], [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]], [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]]
dimension= 3


In [18]:
import numpy as np
nli=np.array([1,2,3,4],ndmin=10)
print(nli)
print(nli.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [21]:
arr_zero1=np.zeros(4)
print(arr_zero1)
print()
arr_zero2=np.zeros((3,4))
print(arr_zero2)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
arr_one1=np.ones(4)
print(arr_one1)
print()
arr_one2=np.ones((3,4))
print(arr_one2)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
arr_empty1=np.empty(4)
print(arr_empty1)
print()
arr_empty2=np.empty((3,4))
print(arr_empty2)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
arr_r1=np.arange(5)
print(arr_r1)

[0 1 2 3 4]


In [32]:
arr_dgnl=np.eye(3)
print(arr_dgnl)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
arr_lin=np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


### random

In [64]:
import numpy as np
li=np.random.rand(5)
print(li)

[0.39188655 0.09001285 0.24000006 0.24757609 0.23475607]


In [50]:
li=np.random.randn(5)
print(li)

[-1.11074667 -0.20790704 -0.60896296 -0.52931566 -0.70598691]


In [79]:
li=np.random.ranf(5)
print(li)

[0.07061191 0.0851565  0.6409046  0.12570398 0.45914826]


In [87]:
li=np.random.randint(5,20,5)
print(li)

[16  5 15 14 19]
